INSERT INTO category (category_name) VALUES ('Electronics');
INSERT INTO category (category_name) VALUES ('Books');
INSERT INTO category (category_name) VALUES ('Clothing');
INSERT INTO category (category_name) VALUES ('Home & Kitchen');
INSERT INTO category (category_name) VALUES ('Sports');
INSERT INTO category (category_name) VALUES ('Beauty & Personal Care');
INSERT INTO category (category_name) VALUES ('Toys & Games');
INSERT INTO category (category_name) VALUES ('Groceries');
INSERT INTO category (category_name) VALUES ('Furniture');
INSERT INTO category (category_name) VALUES ('Automotive');
INSERT INTO category (category_name) VALUES ('Mobile Phones');
INSERT INTO category (category_name) VALUES ('Laptops');
INSERT INTO category (category_name) VALUES ('Cameras');
INSERT INTO category (category_name) VALUES ('Smart Watches');
INSERT INTO category (category_name) VALUES ('Health & Fitness');
INSERT INTO category (category_name) VALUES ('Pet Supplies');
INSERT INTO category (category_name) VALUES ('Baby Products');
INSERT INTO category (category_name) VALUES ('Jewelry');
INSERT INTO category (category_name) VALUES ('Footwear');
INSERT INTO category (category_name) VALUES ('Office Supplies');
INSERT INTO category (category_name) VALUES ('Musical Instruments');
INSERT INTO category (category_name) VALUES ('Garden & Outdoor');
INSERT INTO category (category_name) VALUES ('Gaming');
INSERT INTO category (category_name) VALUES ('Stationery');
INSERT INTO category (category_name) VALUES ('Kitchen Appliances');
INSERT INTO category (category_name) VALUES ('Home Decor');
INSERT INTO category (category_name) VALUES ('Travel Accessories');
INSERT INTO category (category_name) VALUES ('Bags & Luggage');
INSERT INTO category (category_name) VALUES ('Industrial Supplies');
INSERT INTO category (category_name) VALUES ('Software');